collector/bgp.go
collector/bgp_test.go

Hi,
I've added scraping of `show evpn vni json` outputs, to gather data the additional *EVPN* related metrics:
* `frr_bgp_l2vpn_evpn_num_macs_count_total`: Number of known MAC addresses in a given VxLAN
* `frr_bgp_l2vpn_evpn_num_arp_nd_count_total`: Number of ARP / ND entries in a given VxLAN
* `frr_bgp_l2vpn_evpn_num_remote_vteps_count_total`: Number of known remote VTEPs
Labels for these 3 metrics are `tenantVrf`, `type` (L2 / L3), `vni`, `vxlanIf`.
Also I've implemented testing for the new features and while doing this, fixed the failing tests (#12 ).
Please review

Added EVPN features, closes #12

---

README.md

Explicitly state that `--collector.bgp.peer-descriptions.plain-text` requires `--collector.bgp.peer-descriptions` flag.

Update peer description label documentation

---

README.md
collector/bfd.go
collector/bfd_test.go
collector/ospf.go
frr_exporter.go

Add a FRR BFD collector to the frr_exporter.
Exposes 3 metrics based on the _vtysh -C "show bfd peers json"_:
- frr_bfd_peer_count{} - total number of bfd peers connected
- frr_bfd_peer_uptime{local=10.10.141.81,peer=10.10.141.61} - The time in seconds the bfd connection to the peer has been up
- frr_bfd_peer_state{local=10.10.141.81,peer=10.10.141.61} - The up/down state of the bfd peer connection

Add BFD collector 

---

README.md
collector/bgp.go

In recent FRRs, there is a `PfxSnt` field in the output of `show bgp summary json`. ( https://github.com/FRRouting/frr/commit/37d4e0dfabcc47e874987d8b7ec27d0f05376705 )  
This field could see only if  peer state is "Established".  
This can be used as `frr_bgp_peer_prefixes_advertised_count_total` metrics.  
`--collector.bgp.advertised-prefixes` option left for old FRRs.
example output (FRR `7.3`)  
```json
{
"ipv4Unicast":{
"routerId":"172.31.0.3",
"as":4200000003,
"vrfId":0,
"vrfName":"default",
"tableVersion":3192766,
"ribCount":81,
"ribMemory":14904,
"peerCount":2,
"peerMemory":41856,
"peerGroupCount":1,
"peerGroupMemory":64,
"peers":{
"ens4f0":{
"hostname":"edge000a",
"remoteAs":4200049152,
"version":4,
"msgRcvd":10393531,
"msgSent":10104089,
"tableVersion":0,
"outq":0,
"inq":0, …
```

support for PfxSnt field

---

collector/bgp.go

If there is no vrf/vxlan interface/vni configured on the host, the
following command 'show evpn vni json' won't return anything.
Before attempting to unmarshall what is returned, we should check that
the length of the slice is different from 0.
Fixes #29

bugfix, l2vpn: do not try to unmarshall empty l2vpn evpn summary slice

---

collector/collector.go
collector/command.go
frr_exporter.go

If you have multiple instances of frr running on the same machine
(e.g. because they are responsible for different network namespaces)
this option is necessary to be able to export metrics from all frr
instances.
vtysh supports the -N option (they call it pathspace, the prefix for frr config)
This commit adds support for passing -N to vtysh

Add frr.vtysh.pathspace option (=> vtysh -N)

---

collector/collector.go
collector/command.go

If I run the exporter without pathspace param, or with the default param,
it will crash:
```
[12:28:29] root@XXX:~# /home/sneubauer/frr_exporter
INFO[0000] Starting frr_exporter (version=, branch=, revision=) on :9342  source="frr_exporter.go:133"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x877e80]
goroutine 36 [running]:
github.com/tynany/frr_exporter/collector.execVtyshCommand(0xc000318e30, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
/Users/sneubauer/work/github/syseleven/frr_exporter/collector/command.go:26 +0x120
github.com/tynany/frr_exporter/collector.getOSPFInterface(...)
/Users/sneubauer/work/github/syseleven/frr_exporter/collector/ospf.go:81 …
```

Fix segmentation fault when pathspace option is not provided

---

collector/bgp.go
collector/vrrp.go

Because in the BGP and VRRP collectors, the error list
will never be reset, the collectors report as down forever
until the exporter is restarted after just one error

Fix bug where collector will stay down forever after any error

---

Makefile

https://github.com/prometheus/promu/releases/tag/v0.12.0

promu: bump version to 0.12.0

---

collector/bgp.go

If using collector.bgp.peer-descriptions.plain-text errors the function
is stopped from generating json unmarshalling errors. 
A conditional statement is applied to detect kingpin for 
bgpPeerDescsText
fixes #45

Fix json unmarshall error when plain text peer description flag selected

---

collector/bgp.go
collector/ospf.go
collector/pim.go
collector/vrrp.go

Run
```
goimports -w .
```
Ensure that there is a newline between each function. Remove newlines around single lines to group them visually.
Maybe you could add a check to the CI to ensure the code is formatted nicely on every PR.

Format code with goimports use consistent newlines

---

collector/bgp.go

Commit 120ff2ab06679060640610f2765633c672f8c944 changed `getBGPPeerDesc` to parse the JSON output from the `vtysh` command `show bgp neighbors` instead of `show run bgpd`, but forgot to update the `vtysh` command.
Successfully tested in our environment.
It would be nice if there were test cases that cover this kind of issue.
Closes: https://github.com/tynany/frr_exporter/issues/52

Fix getting the BGP peer description

---

collector/bfd.go
collector/bgp.go
collector/ospf.go
collector/pim.go
collector/vrrp.go

Putting an `else` right after a `return` will increase the indentation level. Remove the `else` to keep the error-free code path in the top level.

Do not use else after return

---

collector/bgp.go

- Fix https://github.com/tynany/frr_exporter/issues/56.
Before:
```
level=info ts=2021-12-14T07:52:42.965Z caller=frr_exporter.go:65 msg="Starting frr_exporter" version="(version=, branch=, revision=)"
level=info ts=2021-12-14T07:52:42.965Z caller=frr_exporter.go:66 msg="Build context" build_context="(go=go1.17, user=, date=)"
level=info ts=2021-12-14T07:52:42.966Z caller=frr_exporter.go:67 msg="Listening on address" address=:9342
level=info ts=2021-12-14T07:52:42.966Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
level=debug ts=2021-12-14T07:52:44.403Z caller=collector.go:124 msg="collector succeeded" name=bgp duration_seconds=0.000391316
level=debug ts=2021-12-14T07:52:44.403Z caller=collector.go:124 msg="collector succeeded" name=ospf duration_seconds=0.002571372
panic: …
```

fix missing bgp l2vpn descriptions

---

README.md

Wrap long lines in `README.md` and add newlines after titles to make the raw Markdown file more readable.

README.md: Wrap long lines

---

README.md
internal/frrsockets/frrsockets.go

My previous PR failed linting in CI and it was not noticed until after it was merged to master. 
This fixes the linting error and adds instructions to the README on how to run the linting tool locally before submitting a PR.

Fixup linting error in CI; add linting to readme

---

.github/workflows/docker_upload.yml

- Upload on every push to main for latest
- Also tag the release version when a new release is made
- i.e. when you release a very the Git tag name is used for docker image tagging too - e.g. v1.1.1
- Also build a arm64/aarch64 build (e.g. for raspberry pi / apple M1)
This is in use for many project I contribute to.
- I'd like to run your frr_exporter on arm64/aarch64 boxes
- On my raspberry pi in my RV is one example
- Before merging add two secrets to you GitHub repo:
- DOCKERHUB_USERNAME
- DOCKERHUB_SECRET
- This secret need to be a dockerhub secret you generate here: https://hub.docker.com/settings/security
How to add GitHub secrets: https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md
Merge away and it should upload :)

Add Docker Upload Action + build arm64 images

---

internal/frrsockets/frrsockets.go
internal/frrsockets/frrsockets_test.go

This is a pretty aggressive cleanup of the `executeCmd` Unix socket read/write function to be a bit more compact and cause fewer allocations.
Also add simple mock / test for this function.

Refactor executeCmd func and add unit tests / mock

---

internal/frrsockets/frrsockets.go
internal/frrsockets/frrsockets_test.go

filepath.Join is the preferred way to assemble paths elegantly, and the result is cleaned by filepath.Clean anyway.

Use filepath.Join in place of simple string concatenation

---

frr_exporter.go
go.mod
go.sum

This requires a small change, since `web.ListenAndServe()` now takes a struct `*web.FlagConfig` instead of just a string for the TLS configfile.

bump exporter-toolkit to v0.8.0

---

collector/command.go
internal/frrsockets/frrsockets.go
internal/frrsockets/frrsockets_test.go

`show bfd peers` requires vty session to be in 'enable' mode. Since `vtysh` defaults to 'enable' mode anyway, follow the same method.
Closes: #100

Implement support for reading bfdd.vty socket directly

---

collector/bfd.go
collector/bgp.go
collector/collector.go
collector/ospf.go
collector/pim.go
collector/vrrp.go
frr_exporter.go
go.mod
go.sum

Prometheus and its associated libraries are moving away from go-kit/log, and instead will use the built-in log/slog from the Go standard library, which is available since Go 1.21.
prometheus/exporter-toolkit v0.13.0 implemented a non-backwards-compatible change to the web.ListenAndServe() function (among others), and now expects to be supplied a *slog.Logger.
For the end user, this change is minimal. Logs may have a subtly different appearance, but are still in logfmt, so log parsers such as Loki should not trip up on this.

Adopt structured logging using log/slog

---

Dockerfile

Bump the patch version to 10.1.2 to include bug fix with CVEs (from 40 to 2)
Following is the scene result from trivy.
```
Total: 40 (UNKNOWN: 4, LOW: 6, MEDIUM: 19, HIGH: 9, CRITICAL: 2)
┌──────────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────────┐
│       Library        │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                            Title                            │
├──────────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼─────────────────────────────────────────────────────────────┤
│ libcrypto3           │ CVE-2024-6119  │ MEDIUM   │ fixed  │ 3.1.6-r2          │ 3.1.7-r0      │ openssl: Possible denial of …
```

Upgrade to frr 10.1.2 to fix CVE-2024-45491

---

collector/bgp.go

This PR introduces new metrics to report the number of accepted and filtered routes for each BGP peer. The metrics are exported only when the `--collector.bgp.accepted-filtered-prefixes` flag is enabled.
The following two metrics are newly available:
* `frr_bgp_peer_prefixes_accepted_count_total`
* `frr_bgp_peer_prefixes_filtered_count_total`

Add BGP accepted/filtered prefixes count metric

---

collector/bgp.go
collector/bgp_test.go
collector/collector_test.go
collector/ospf_test.go
collector/route.go
collector/testdata/show_ip_bgp_vrf_all_nexthop.json

This PR adds the BGP nexthop peering interface.
That allows the detection on which physical interface the peering is currently running.
This change sits behind the `collector.bgp.next-hop-interface` flag.

Adding BGP Peer Nexthop Interface
